logging:
  level:
    org.springframework: info
    org.hibernate:
      SQL: info

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        generate_statistics: true
    generate-ddl: true
  flyway:
    user: root
    password: root
    url: jdbc:h2:mem:testdb
    enabled: false
