spring:
  application:
    name: "MonolithArchitecture"
  profiles:
    active: "@spring.profiles.active@"
  threads:
    virtual:
      enabled: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false
  datasource:
    hikari:
      auto-commit: false
  main:
    lazy-initialization: true
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=10,expireAfterAccess=300s
    cache-names: jsonPlaceHolder, userCache, todoCache, adminCache, fingerprintCache
  mvc:
    apiversion:
      use:
        header: X-API-Version
  security:
    filter:
      dispatcher-types: async, error, request
    oauth2:
      client:
        provider:
          monolith-keycloak:
            issuer-uri: ${WELLDEV.KEYCLOAK.ISSUER-URI}
        registration:
          keycloak:
            provider: ${WELLDEV.KEYCLOAK.REALM}
            authorization-grant-type: authorization_code
            client-id: ${WELLDEV.KEYCLOAK.CLIENT-ID}
            client-secret: ${WELLDEV.KEYCLOAK.CLIENT-SECRET}
            scope:
              - openid
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/monolith-keycloak/protocol/openid-connect/certs
          issuer-uri: http://localhost:7080/realms/monolith-keycloak
springdoc:
  swagger-ui:
    path: /swagger-ui.html
application:
  keycloak:
    server-url: ${WELLDEV.KEYCLOAK.SERVER.URL}
    realm: ${WELLDEV.KEYCLOAK.REALM}
    client-id: ${WELLDEV.KEYCLOAK.CLIENT-ID}
    client-secret: ${WELLDEV.KEYCLOAK.CLIENT-SECRET}
  aes:
    secret-key: ${WELLDEV.AES.SECRET.KEY}
server:
  port: 8080
  tomcat:
    threads:
      # Min num of threads always kept alive
      min-spare: 20
      # Max threads available to serve requests
      max: 200
    connection-timeout: 20000
    keep-alive-timeout: 15000 # Time Tomcat awaits for the next request before closing connection
    max-keep-alive-requests: 100 # Max requests served over a single connection
    accept-count: 100
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/xml, text/plain
    min-response-size: 1024