openapi: 3.0.3
info:
  title: Monolith Architecture - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost:8080
    description: Local Server
tags:
  - name: auth
    description: Authentication
  - name: jsonplaceholder
    description: Get all dummy data from jsonplaceholder
  - name: user
    description: Operations about user
security:
  - bearerHttpAuthentication: []
paths:
  /api/v1/auth/register:
    post:
      tags:
        - auth
      summary: "Register new user"
      operationId: registerUser
      parameters:
        - $ref: '#/components/parameters/FingerprintHeader'
        - $ref: '#/components/parameters/ApiVersionHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: User Registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    nullable: false
                  refresh_token:
                    type: string
                    nullable: false
        '401':
          description: Unauthorized

  /api/v1/auth/authenticate:
    post:
      tags:
        - auth
      summary: "Authenticate User"
      operationId: authenticateUser
      parameters:
        - $ref: '#/components/parameters/ApiVersionHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authenticationRequest'
      responses:
        '200':
          description: User authenticate successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    nullable: false
                  refresh_token:
                    type: string
                    nullable: false
        '401':
          description: Unauthorized
  /api/v1/refresh-token:
    post:
      tags:
        - auth
      summary: "Refresh Token"
      operationId: refreshToken
      parameters:
        - $ref: '#/components/parameters/ApiVersionHeader'
      responses:
        '200':
          description: Refresh token Successful
        '401':
          description: Unauthorized
  /api/v1/logout:
    post:
      tags:
        - auth
      summary: logout
      parameters:
        - $ref: '#/components/parameters/ApiVersionHeader'
      responses:
        '200':
          description: "Logout Successful"
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer token using a JWT
      type: http
      scheme: Bearer
      bearerFormat: JWT
  parameters:
    ApiVersionHeader:
      name: X-API-Version
      in: header
      required: true
      schema:
        type: string
        default: "1.0"
        example: "1.0"
    FingerprintHeader:
      name: X-Fingerprint
      in: header
      required: false
      schema:
        type: string
        example: "abc123fingerprint"
  schemas:
    UserRequest:
      type: object
      properties:
        firstName:
          title: Firstname
          type: string
          nullable: false
          maxLength: 50
          example: John
        lastName:
          title: Lastname
          type: string
          nullable: false
          maxLength: 50
          example: Doe
        age:
          title: Age
          type: integer
          nullable: false
          format: int32
          maximum: 16
          exclusiveMinimum: false
          example: 16
        email:
          title: E-mail
          type: string
          format: email
          nullable: false
        username:
          title: Username
          type: string
          nullable: false
          example: test
        role:
          title: Role
          type: string
          enum:
            - ADMIN
            - USER
          nullable: false
          example: USER
        password:
          title: Password
          type: string
          nullable: false
          example: P@ssW0rd%
    authenticationRequest:
      type: object
      properties:
        username:
          title: Username
          type: string
          nullable: false
          example: test
        password:
          title: Password
          type: string
          nullable: false
          example: P@ssW0rd%
    User:
      type: object
      properties:
        id:
          type: integer
          nullable: false
          format: int64
          maxLength: 50
          example: 1
        firstname:
          type: string
          nullable: false
          maxLength: 50
          example: "Leanne"
        lastname:
          type: string
          nullable: false
          maxLength: 50
          example: "Graham"
        age:
          type: integer
          nullable: false
          format: int64
          example: 12
        gender:
          type: string
          nullable: false
          enum:
            - MALE
            - FEMALE
            - OTHER
        username:
          type: string
          nullable: false
          example: "Bret"
        email:
          type: string
          nullable: false
          example: "test@test.com"
        password:
          type: string
          nullable: false
          example: "password"
        role:
          type: string
          nullable: false
          enum:
            - USER
            - ADMIN
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/Token'
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        userDto:
          $ref: '#/components/schemas/User'
        title:
          type: string
          example: delectus aut autem
        completed:
          type: boolean
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        userDto:
          $ref: '#/components/schemas/User'
        title:
          type: string
          example: delectus aut autem
        body:
          type: string
          example: delectus aut autem
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        post:
          $ref: '#/components/schemas/Post'
        email:
          type: string
          example: test@test.com
        body:
          type: string
          example: delectus aut autem
        name:
          type: string
          example: delectus aut autem
    Token:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        token:
          type: string
          nullable: false
        tokenType:
          type: string
          nullable: false
          enum:
            - BEARER
        revoked:
          type: boolean
          nullable: false
        expired:
          type: boolean
          nullable: false
        user:
          $ref: "#/components/schemas/User"