apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monolith-architecture
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Bigorno12/monolith-architecture.git'
    targetRevision: main
    path: infra/k8s/manifest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true