name: Main CI Orchestrator

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: write
      security-events: write
      checks: write
      pull-requests: write

  lint:
    needs: build
    uses: ./.github/workflows/lint.yml

  unit-tests:
    needs: build
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    permissions:
      checks: write

  integration-tests:
    needs: build
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
    permissions:
      checks: write

  security:
    needs: [unit-tests, integration-tests]
    uses: ./.github/workflows/security.yml
    permissions:
      security-events: write
      actions: read
      contents: read

  tag:
    needs: security
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/tag.yml
    permissions:
      contents: write

  docker-publish:
    needs: security
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write

  build-gate:
    needs:
      - build
      - lint
      - unit-tests
      - integration-tests
      - security
      - tag
      - docker-publish
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check pipeline result
        env:
          BUILD: ${{ needs.build.result }}
          LINT: ${{ needs.lint.result }}
          UNIT_TESTS: ${{ needs.unit-tests.result }}
          INTEGRATION_TEST: ${{ needs.integration-tests.result }}
          SECURITY: ${{ needs.security.result}}
          TAG: ${{ needs.tag.result }}
          DOCKER_PUBLISH: ${{ needs.docker-publish.result }}
        run: |
          RESULTS=("$BUILD" "$LINT" "$UNIT_TESTS" "$INTEGRATION_TEST" "$SECURITY" "$TAG" "$DOCKER_PUBLISH")

          for result in "${RESULTS[@]}"; do
            if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
              echo "❌ Pipeline failed or was cancelled"
              exit 1
            fi
          done

          echo "✅ Pipeline passed successfully!"