name: Linting Module

on:
  workflow_call:


jobs:
  spotless-check:
    name: Code Formatting (Spotless & Ktlint)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v7.0.0

      - name: Stepup Java Environment
        uses: ./.github/setup-java-env

      - name: Verify Code Formatting
        run: mvn spotless:check
