name: Unit Test Module

on:
  workflow_call:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Setup Java Environment
        uses: ./.github/setup-java-env
        with:
          maven-opts: '-Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=256m'

      - name: Run Unit Test
        run: mvn -B test --file pom.xml

      - name: Publish Unit Tests Report
        uses: dorny/test-reporter@v3
        if: always()
        continue-on-error: true
        with:
          name: Maven Unit Test
          path: "**/target/surefire-reports/TEST-*.xml"
          reporter: java-junit
          fail-on-error: 'false'